### PR TITLE
Specific encoding and bom support

### PR DESCRIPTION
**Pull request by LostKobrakai**
In regards to #45

### CODE REVIEW

**Comment by josevalim** [comment]
Hi @LostKobrakai!

Sorry, I am afraid I was not clear in the first comment. I think the best way to tackle this is to change the binary matching syntax and code to work on UTF-16 upfront, instead of forcing a pass on everything. Also note that the `:bom` flag is already support on `File.stream!`, so we don't  need to handle it here. The correct is if users pass the flag to `File.stream!` itself. We should handle bom only on full strings (and handle it only once).

On dumping, however, we will have to do a post pass after all of the data has been encoded.

**Comment by josevalim** [comment]
Actually, let me play with these ideas a bit. I will follow up later today. Thanks!

**Comment by LostKobrakai** [comment]
To be honest, the dumping part is the one I'm most interested in, so feel free to change how parsing is handled.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
